version: '3'
services:
  cypress:
    image: cypress
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    container_name: cypress
    networks:
      - cypress-network
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
      - CYPRESS_BACKEND_URL=http://backend:8080
      - DISPLAY
    entrypoint: cypress open --project /e2e

networks:
  cypress-network:
    external: true