version: '3.3'
services:
  backend:
    build: .
    image: backend 
    container_name: backend
    networks:
      - cypress-network
    environment:
      - FRONTEND_URL=http://frontend:3000

networks:
  cypress-network:
    external: true