version: '3'
services:
  backend:
    build: .
    image: backend 
    container_name: backend
    networks:
      - cypress-network
    environment:
      - FRONTEND_URL=http://frontend:3000

networks:
  cypress-network:
    name: 'cypress-network'
    driver: 'bridge'
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
