name: Cypress Tests

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container: cypress/included:9.4.1
    steps:
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Start Backend Server
        run: ./gradlew :backend:bootJar
      - run: java -jar backend/build/libs/backend-0.0.1-SNAPSHOT.jar &

      - name: Install Dependencies
        working-directory: ./frontend-react
        run: npm ci
      - name: Build Frontend
        working-directory: ./frontend-react
        run: npm run build
      - name: Start Frontend Server
        working-directory: ./frontend-react
        run: npm run start

      - name: Cypress Run e2e Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./tests-cypress
        env:
          CYPRESS_BACKEND_URL: http://localhost:8080
          CYPRESS_baseUrl: http://localhost:3000
      
      - name: Upload Screenshot Artifacts
        uses: actions/upload-artifact@v3
        with:
            name: cypress-screenshots
            path: cypress/screenshots
            # if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Upload Video Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          # if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
