name: Full Test Suite

on:
  push:
    branches:
      - main

jobs:
  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run Backend Unit Tests
      run: ./gradlew :backend:test

    - name: Run Backend Integration Tests
      run: ./gradlew :tests-backend-integration:test

      
  frontend_unit_tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-react

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Frontend Unit Tests
        run: npm test
  

  cypress_tests:
    name: Cypress Tests
    needs: 
      - backend_tests
      - frontend_unit_tests

    runs-on: ubuntu-latest

    container: cypress/included:9.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Start Backend Server
        run: |
          ./gradlew :backend:bootJar
          java -jar backend/build/libs/backend-0.0.1-SNAPSHOT.jar &

      - name: Start Frontend Server
        working-directory: ./frontend-react
        run: |
          npm ci
          npm install pm2 -g
          pm2 start --name frontend npm -- start 

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./tests-cypress
          wait-on: "http://localhost:8080, http://localhost:3000"
        env:
          CYPRESS_BACKEND_URL: "http://localhost:8080"
          CYPRESS_baseUrl: "http://localhost:3000"
      
      - name: Stop Frontend Server
        if: always()
        run: pm2 stop frontend 

      - name: Upload Screenshot Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: cypress-screenshots
            path: tests-cypress/cypress/screenshots
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Upload Video Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: tests-cypress/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
