name: Full Test Suite

on:
  push:
    branches:
      - main

jobs:
  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run Backend Unit Tests
      run: ./gradlew :backend:test

    - name: Run Backend Integration Tests
      run: ./gradlew :tests-backend-integration:test

      
  frontend_unit_tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-react

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Frontend Unit Tests
        run: npm test
